.gitignore, README.md, host_vars/127.0.0.1, host_vars/127.0.0.1/main.yml, roles/piper/tasks/main.yml
Requires a file `charon_credentials.yml` to be put under `host_vars/127.0.0.1/`, because it wasn't possible to have several var files under `roles/ngi_pipeline/defaults` (a `main.yml` already exists there). 
As a consequence `host_vars/127.0.0.1.yml` is also renamed to `host_vars/127.0.0.1/main.yml`, and the gatk key is now supposed to be placed under `playbooks/files` instead of `roles/piper/files` to make it a little bit more similar to the charon credentials.
=> Charon credentials

README.md, host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/defaults/main.yml, roles/ngi_pipeline/files/create_ngi_pipeline_dirs.sh, roles/ngi_pipeline/tasks/main.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/piper/tasks/prereqs.yml, sync.py
- Mention required setgid changes and don't keep backups of confs 
- Create log and db dir under project areas instead. Requires that the script `/lupus/ngi/resources/create_ngi_pipeline_dirs.sh` is run by a funk account with a specific project id as argument. 
- Use the delete flag when syncing.
=> Move db log

roles/tarzan/README.md, roles/tarzan/defaults/main.yml, roles/tarzan/tasks/dependencies.yml, roles/tarzan/templates/cassandra.yaml.j2
Installs an other Kong requirement: serf. 
Initial config of Cassandra to at least make it boot up sensible. 
Have verified by starting it manually in foreground with `cassandra -f` on the cluster, and a manual start of Kong with `kong -c /lupus/ngi/conf/webproxy.yml` at least communicates with it and seems to setup the relevant data storage entities. 
The current show stopper is that Kong afterwards aborts with a: 
```
[ERR] nginx: [emerg] at least OpenSSL 1.0.2e required but found OpenSSL 1.0.1e-fips 11 Feb 2013
[ERR] Could not start Kong
```
=> Cassandra conf

host_vars/127.0.0.1/main.yml, roles/tarzan/README.md, roles/tarzan/defaults/main.yml, roles/tarzan/tasks/dependencies.yml, roles/tarzan/tasks/main.yml
- Compile openresty with newer version of openssl than the one provided from the system. 
- Set correct `LUA_PATH` and `LUA_CPATH` env vars for funk_004 user.
These two changes gets Kong working. After running
- `cassandra -f `
- `kong -c /lupus/ngi/conf/webproxy.yml`
a `curl localhost:8001` will return a JSON payload from the Kong server.
=> Newer version of openssl for openresty

roles/tarzan/defaults/main.yml, roles/tarzan/tasks/main.yml, roles/tarzan/templates/kong.yml.j2
- Make serf and Kong admin interface only listen to localhost.
- Change kong https port to 4444 and non-https to 8888
- Need escaping of lua env vars to not get bash errors 
- Need to add some system lua paths to the lua envs for module system lmod to function, as it is also using lua. Might be a future error source.
- Spawn 4 nginx worker processes instead of the default "auto", which on irma1 will spawn 16 processes (number of CPU cores)
=> Tarzan tuning

sync.py
as that will cause a lot of errors and warnings when an operator tries to update a directory created by an other user.
=> Don't try to update the timestamps for directories, 

roles/func_accounts/templates/crontab_upps.j2, roles/tarzan/defaults/main.yml, roles/tarzan/tasks/dependencies.yml, roles/tarzan/tasks/main.yml, roles/tarzan/templates/kong.yml.j2, roles/tarzan/templates/supervisord_kong.conf.j2
Set the file permission correctly for everything installed under `sw/tarzan/`. A ugly hack is necessary on L68-70 in `tasks/main.yml` that sets the permissions for group and others manually, because it seems some of the installation/compilation steps doesn't respect the umask properly set (?!). This is only done on the files owned by the current user, to limit the amount of errors. So it is expected that each user that runs this role actually runs the complete role so that the permissions gets updated for all new files added. 
Installs the `serf` software that helps kong with cluster discovery. 
Setups proper logging directory for cassandra. 
Launches cassandra via Uppsala's supervisord instance, but it doesn't seem to work easily for kong due to how it spawns sub-processes (nginx + serf) …
=> Tarzan supervisor

roles/tarzan/README.md
- Manually configured the web proxy on irma1 for authenticated access to Uppsala's ngi_pipeline web API 
- Documented the steps in Tarzan's README so that it can be reproduced for future downstream APIs
Note that the token created in these steps need manual safekeeping at some appropriate location.
=> Configure web proxy for Uppsala's ngi_pipeline web API 

roles/tarzan/defaults/main.yml
Updated cassandra version since 2.2.5 doesn't exist at the source.
If you want to pull 2.2.5 from another source instead, feel free to comment.
=> Cassandra 2.2.5 doesn't exist, updating to 2.2.6

roles/ngi_pipeline/templates/sourceme_common.sh.j2
Solves https://github.com/NationalGenomicsInfrastructure/irma-provision/issues/77
=> Force English locale to get correct decimal separator in pipeline output

install_arteria.yml, roles/arteria-checksum-ws/defaults/main.yml, roles/arteria-checksum-ws/tasks/2_install_config.yml, roles/arteria-checksum-ws/tasks/main.yml, roles/arteria-siswrap-ws/defaults/main.yml, roles/arteria-siswrap-ws/tasks/main.yml, roles/arteria-siswrap-ws/tasks/sisyphus.yml, roles/arteria-siswrap-ws/templates/siswrap_app.config.j2
Sets up production and staging specific paths and values in the form of `/lupus/ngi/conf/arteria/{checksum,siswrap}/{production,staging}` and `/lupus/ngi/sw/arteria/{checksum,siswrap}_{src,venv}/{production,staging}`, and updates Uppsala's `supervisord.conf` to listen on different ports depending on environment. 
What version to install is controlled via the vars `arteria_checksum_environment` and `arteria_checksum_version` (and corresponding for `siswrap`). Can be overridden on the command line when the operator wants to install a new version into staging e.g.
=> Support production and staging versions of Arteria services

roles/ngi_reports/defaults/main.yml, roles/ngi_reports/files/make_report.sh, roles/ngi_reports/tasks/dependencies.yml, roles/ngi_reports/tasks/main.yml, roles/ngi_reports/templates/make_report.sh.j2, roles/ngi_reports/templates/texlive.profile.j2
TexLive wasn't properly installed in the past. This was ignored as NGI Reports had ten other things not making it functional. This update makes sure TexLive is actually installed and used.
Feel free to verify this a bit extra. The installation takes forever, so I've only quickly verified it once.
=> NGI Reports texlive installation

roles/arteria-siswrap-ws/defaults/main.yml, roles/arteria-siswrap-ws/tasks/sisyphus.yml
Needed so we can set some appropriate env vars ($PATH) before running cpanm. By removing anaconda from $PATH cpanm will not pick up the version of libxml2.so that it bundles, which otherwise conflicts with the system installed version under /usr/lib64.
=> Install some CPAN modules manually via cpanm 

install_arteria.yml
Includes support for running the Sisyphus aeacus-report and aeacus-stats scripts via API wrappers.
=> Install latest version of arteria-siswrap into production

sync.py
Sisyphus (that is used by some of the Arteria web services) requires the .git dir to exist in the installed folder, so that it e.g. can read out version information for tracability reasons, etc. This is the easiest fix for this.
=> Sync .git dirs due to dependencies that need to read it

roles/multiqc/tasks/main.yml, roles/multiqc/templates/multiqc_config.yml.j2, roles/ngi_reports/defaults/main.yml
Due to the NGI submodule of MultiQC causing problems for Uppsala, the config for MultiQC has now been separated into two.
NGI Reports has also been updated to fix an invalid libprep issue.
=> New ngi_reports version, multiqc config separation

roles/tarzan/README.md, roles/tarzan/defaults/main.yml, roles/tarzan/tasks/main.yml, roles/tarzan/templates/kong.yml.j2
Today we're using an auto-generated self signed SSL cert located at `/proj/ngi2016001/private/ngi_pipeline/log/tarzan/ssl`. This causes clients to warn about it being self signed. To circumvent this one can add the contents of the cert in the client's CA bundle (e.g. in the one included in Python's `request` library, which is used by Stackstorm). 
But apparently these auto-generated certs are only valid for 1 month, so the client is still complaining as the current cert has expired. 
Therefore we're now instead manually generating a self-signed cert that we put in the Tarzan conf dir.
=> Tarzan: use self signed SSL cert valid for 4 years

roles/tarzan/templates/kong.yml.j2
Kong's template uses an other Jinja pattern `[% %]` due to the embedded nginx conf parses `{{ }}` as well.
=> Fix template syntax error

roles/tarzan/README.md
Apparently the CN field in the cert had to match the hostname for the webproxy exactly.
=> Update cert instructions for required CN field

roles/ngi-rnaseq/tasks/main.yml
Turns out when you do not name the items you are supposed to omit the curly brackets.
Honestly did not expect that at all.
=> Resolved ngi-rnaseq syntax error

roles/multiqc/defaults/main.yml, roles/multiqc/tasks/main.yml, roles/multiqc/templates/multiqc_config.yml.j2
The template used the variable `ngi_hooks` for the parameter `disable_ngi_hooks`which caused a logic error to sneak in. Changed the setting as well as the variable name to prevent this in the future.
Also had to update MultiQC_NGI to handle an uncatched exception.
=> Fixed multiqc problems from latest deployment

roles/multiqc/tasks/main.yml
NGI template was confirmed to always be used in Stockholm. 
Implementation isn't the nicest, but the alternative uses a lot of extra lines.
=> Added ngi template as default for stockholm

roles/ngi_reports/defaults/main.yml, roles/nougat/defaults/main.yml
NouGAT previously had a problem with HiseqX's directory structure.
NGI_Reports now handles HDD deliveries.
Some refactoring of the code for both repos.
=> NouGAT & NGI_Reports version bump

ansible.cfg
This will disable the retry files that are usually created with the same prefix as the playbook. It will clean up the working area a little bit as we're not using this feature at the moment.
=> Disable retry files that clutter working area

roles/tarzan/README.md
Just a brief example to the README on how to list the downstream APIs that have already been registered in the web proxy.
=>  Mention how to list downstream APIs

README.md, host_vars/127.0.0.1/main.yml, install.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, sync.py
This PR asks ngipipeline to use Piper from the module system instead of deploying it ourselves. It also uses the gatk_bundle provided by UPPMAX. 
It has been test deployed under `devel-root` on `irma3` without problems, but no scripts or programs have been tried. There are some values that might need adjustment after more proper testing.
=> Use Piper from module system 

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/templates/create_ngi_pipeline_dirs.sh.j2, roles/ngi_reports/templates/ngi_reports_sthlm.conf.j2, roles/ngi_reports/templates/ngi_reports_upps.conf.j2
This has been bugging me for a while. 
Since /private/ became a sorts of generalized log folder it was really counterintuitive for it to be a subfolder of ngi_pipeline.
=> Removed ngi_pipeline from log dir structure

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/ngi_pipeline/templates/sourceme_common.sh.j2
Previously we only tried to load Piper in the ngipipeline, but it seems to have failed. Probably due to the quotes that ended up in the config. This error wasn't found during testing because parts from the old environment was still present that made ngipipeline fall back to those piper settings instead. 
We're also adding the module load to the shell for interactive usage/testing (and it will also function as a backup of the module load in ngipipeline fails, because then the environment from the shell will be used instead).
=> Load piper in the shell 

README.md, roles/arteria-checksum-ws/defaults/main.yml, roles/arteria-checksum-ws/tasks/2_install_config.yml, roles/arteria-checksum-ws/tasks/main.yml, roles/arteria-siswrap-ws/defaults/main.yml, roles/arteria-siswrap-ws/tasks/main.yml, roles/ngi_pipeline/templates/sourceme_common.sh.j2, tasks/pre-install.yml
This PR mainly updates the Arteria roles so that they use the Irma staging/prod environments instead of having their own internal staging/prod combos. 
It also fixes a bug with `tasks/pre-install.yml` where `proj_root` got set to `/proj` even in staging due to a mistake I made when I added the `set_fact` for `milou_delivery`. I assumed the tasks were in a `block` only evaluated for production setups, but instead it got set all the time. 
Then we're now setting the Bash path explicitly instead of re-using the `PS1` variable, because that didn't work when having a staging env as a personal user (although it did work as a func user in production mode). Having it set like this instead makes it work in both setups though.
=> Fixes and updates to the staging env 

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
This is verified on milou to properly add piper to the sbatch instead of it relying on it being loaded by the user. Props to Denis.
=> Fix to add piper module to sbatch

roles/ngi_pipeline/tasks/main.yml, roles/ngi_pipeline/templates/create_ngi_pipeline_dirs.sh.j2
If ngi_pipeline is ran with a relative flowcell path it checks out the `incoming` directory. As such we should ensure that there always exists one.
Having the recipe create a `denovo` directory for denovo QC rather than relying on a nice user creating one is also a good idea.
=> Added a few dirs to be created

roles/multiqc/defaults/main.yml, roles/multiqc/templates/multiqc_config.yml.j2
This commit updates multiqc to version 0.8 and the multiqc_ngi plugin to version 0.3, both which are largely considered stable. The configuration has also been updated as to store multiqc reports on one of our servers.
=> Multiqc upgrade

host_vars/127.0.0.1/main.yml, tasks/pre-install.yml
`/lupus/ngi/validation_data/` is manually populated with validation data on Irma, but not on irma3. Because `/lupus/ngi/staging/wildwest` is cleaned with every staging sync it is not enough to have static symlinks setup, but we need to re-create them for every deployment. 
A potential problem with this might come up in the future when rsyncing (with the `--delete` flag) as an other user, and if some of these symlinks are supposed to be removed/renamed. Then the rsync might fail with this, as file permissions and symlinks are a different kind of beast. In that case the symlinks will have to be removed manually by the file owner.
=> Create staging links to validation data

roles/nougat/templates/NouGAT_config.conf.j2
NouGAT now runs the NGI environment per default instead of having to manually specify it.
=> Updated nougat config

roles/ngi_pipeline/tasks/main.yml
When we removed the piper role (and started using piper from the module system) we also stopped provisioning the GATK key, because that was a task in the role. Therefore I'm now adding the task to the ngi_pipeline role instead.
=> Provision the GATK key

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/taca/defaults/main.yml
Both of these software were running slightly old versions. Might as well bump these since the tests have to be restarted. The TACA bump is necessary to get the cleanup function running for an unusual situation.
=> NGI Pipeline and TACA version bumps

host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml
Interest in deploying other stuff before ngi_pipeline (again).
Reverted ngi_pipeline to official version.
Updated taca-ngi & TACA to allow specific cluster delivery.
=> Updated taca & taca-ngi, reverted ngi_pipeline to safe version

sync.py
So we need to update the sync script so that pexpect knows what to wait for before sending the user's token.
=> UPPMAX has changed the 2f challenge

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/nougat/templates/NouGAT_config.conf.j2, roles/taca/tasks/main.yml
This updates the TACA delivery config and NGI pipeline config used by Uppsala to have a Uppsala specific email address. That way it gets easier for our bioinformaticians to differentiate between our projects in the mailbox.
=> Mail for Uppsala projects should go to an other address

roles/ngi_pipeline/defaults/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ngi_pipeline/templates/sourceme_site.sh.j2
Use different config files for archiving to PDC depending on if we're logged in as Uppsala or Stockholm.
=> Load PDC archiving settings on login

roles/ngi_pipeline/templates/sourceme_common.sh.j2
Sadly cannot get rid of this as of yet.
Piper is called prior to the execution of the sbatch job. This can hopefully be fixed in NGI_Pipeline, but it has already been long enough of a wait just to get the current version of NGI_Pipeline out.
=> Readded bashrc piper dependency

roles/ngi_reports/defaults/main.yml, roles/standalone_scripts/tasks/main.yml
New NGI_visualizations version is necessary for some of the newest MultiQC features.
Standalone scripts has been requested to be added to path. Since this repo is way more liberal than others, I am adding it the end of PATH to avoid the scripts taking priority in possible future naming conflicts. This will hopefully _never_ happen, but this is at least a minor safeguard for it.
=> Bumped ngi_visual repo, pathed standalone_scripts

roles/taca/templates/site_taca_delivery.yml.j2
As the title suggests, deliveries will now fail if ngi_reports fail to be generated, which is the desired behaviour for Uppsala.
=> make ngi_reports required for Uppsala deliveries

roles/ngi_reports/tasks/main.yml
Having the scripts dir in $PATH causes name collision in some situations when resolving the script name `ngi_reports`, as the one we want to call is located in Anaconda's venv dir (that is also in $PATH). 
The files under the scripts dir are helpers that are needed for functionality though, but it should apparently have been solved through other ways already. This needs to be tested though for certainty.
=> Don't add ngi_reports' script dir to $PATH 

roles/tarzan/tasks/main.yml
This will cause a snapshot to be taken of the Cassandra db (Kong's backend) once a week, so that the normal backup processes that run on `/proj/` dirs can include the files in a well known state. The created snapshots are so minimal (a couple of hundred kb) so no need to do any clean up at the moment.
=> Snapshot Cassandra weekly

host_vars/127.0.0.1/main.yml
This removes the usage of automatic multiqc start completely, since its usefulness is debatable and it ran into a few issues.
=> New ngi-pipeline staging version

roles/standalone_scripts/defaults/main.yml, roles/standalone_scripts/tasks/main.yml, roles/taca/templates/site_fastq_delivery.yml.j2, roles/taca/templates/site_taca_delivery.yml.j2
Recipes now use project name for deliveries.
Standalone scripts version updated to include merge* script.
=> Added ngi_reports for sthlm, updated standalone scripts version

install.yml, roles/anaconda/defaults/main.yml, roles/anaconda/tasks/main.yml, roles/ngi_pipeline/defaults/main.yml, roles/ngi_pipeline/meta/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ugc/defaults/main.yml, roles/ugc/meta/main.yml, roles/ugc/tasks/main.yml, roles/ugc/templates/sourceme_ugc.sh.j2
Initial basic config that UGC can use for delivering runfolders/projects via Mover and SUPR through a helper script (https://github.com/Molmed/delivery). 
As it is setup now they would add a `source /lupus/ngi/production/latest/conf/sourceme_ugc.sh` in their Bash init files, and then whenever they need to do a delivery they can do a `ugc-init` followed by the `python deliver.py .....` command. 
Perhaps UGC needs more features or configs in the future, but this seems sensible as a start.
=> Let UGC deliver data through Mover and SUPR

roles/arteria-delivery-ws/defaults/main.yml, roles/arteria-delivery-ws/meta/main.yml, roles/arteria-delivery-ws/tasks/install.yml, roles/arteria-delivery-ws/tasks/main.yml, roles/arteria-delivery-ws/templates/delivery_logger.config.j2
New arteria-delivery that fixes async problems uses Python v3; therefore we need to install it in a conda environment instead.
=> Make delivery jobs async

roles/taca/templates/site_taca_local.yml.j2
`taca cleanup` have been updated to remove the Undetermined reads, so the required pattern should be defined in the config file.
=> new entry for TACA local config

roles/ngi_pipeline/templates/create_ngi_pipeline_dirs.sh.j2, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Discussed gt_concordance. It is not used by uppsala, but it seems pointless to exclude them from the config. Did however exclude them from the creation of the incoming directories, since it may unlike the config, draw some confusion.
All variabels introduced have been decided to stay, with the exception of the ones pointing to /static/ folders; since the files will be integrated in a later ngi_pipeline push.
=> Further updates to gt_concordance config

roles/ngi-rnaseq/tasks/dependencies.yml
Turns out manually setting SNIC_TMP like this causes some problems when uppsala run piper.
Verified; and since we no longer save workfiles in a write directory - it all works out.
=> Removed SNIC_TMP variable set

host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml
taca -> regex updated to include inhouse projects while cleanup
ngi_pipeline -> fastq_screen doesn't overwrite result when samples where run on mutliple flowcells
=> taca and ngi_pipeline updates

roles/ngi-rnaseq/defaults/main.yml
Could probably switch to versions instead of commit id at this point, but I know the people responsible have a tendency to make hotfixes.
=> NGI-rnaseq release version

roles/ngi_reports/defaults/main.yml, roles/taca/defaults/main.yml
NGI_Reports can now produce reports to project name instead of pid.
TACA now also prints log info to stdout to make errors more apparent.
=> NGI_reports custom outdir, taca prints to stdout

roles/arteria-delivery-ws/tasks/main.yml
Apparently `supervisord` doesn't start a new shell when spawning subprocesses, so we need to do a workaround when launching the `arteria-delivery` webservice, as it is using a `conda` environment instead of the previous services that are using normal Python virtualenvs.
=> Fix supervisord syntax so that arteria-delivery can start

roles/arteria-delivery-ws/defaults/main.yml
The outputed ID can apparently contain more dashes than expected.
=> Fix bug in parsing mover id from mover

roles/ngi_reports/defaults/main.yml, roles/taca/templates/site_fastq_delivery.yml.j2, roles/taca/templates/site_taca_delivery.yml.j2
Note that this only affects project_summary (which isn't used by uppsala). All other functions will deliver to `pid` as per usual.
=> Changed sthlm delivery to pname-pid

roles/arteria-delivery-ws/defaults/main.yml, roles/arteria-delivery-ws/templates/delivery_app.config.j2
This change to arteria-delivery calls a specific version of mover (manually set path). To be tested in staging.
=> Arteria-delivery: Call specific version of mover

README.md, roles/arteria-delivery-ws/tasks/main.yml
Have to start arteria-delivery directly for it to work with supervisord. Also updates the staging example so that it starts in the same way.
=>  	Start arteria-delivery correctly via supervisord

host_vars/127.0.0.1/main.yml, roles/ngi-rnaseq/defaults/main.yml, roles/ngi_pipeline/templates/create_ngi_pipeline_dirs.sh.j2, roles/ngi_reports/defaults/main.yml
Largely just version updating a few tools. Reasons are posted in the commitmessage.
Rolling back {{ deployment_version }} since it doesn't work for production, and the few cases one needs it doesn't warrant the time to make a proper if case.
=> Version upgrades of various tools

README.md, roles/tarzan/tasks/main.yml, roles/tarzan/templates/stop_kong.sh.j2
Just a little script to make it easier to stop the Kong services, so that it is quicker to relaunch them after a new Irma production environment has been rolled out.
=> Make it easier to stop Kong services

roles/arteria-delivery-ws/defaults/main.yml, roles/tarzan/tasks/main.yml
Use latest version of arteria-delivery that correctly parses the IDs returned from Mover. 
PR also fixes a syntax error in the Tarzan role.
=> Fix parsing of Mover IDs in arteria-delivery

install.yml, roles/misc-tools/defaults/main.yml, roles/misc-tools/tasks/main.yml
added a new role for general purpose tools, that are not necessarily directly pipeline related but helpful nonetheless. The first tool in that role is `jq`, a command-line program for processing and pretty-printing JSON.
=> added role for miscellaneous tools, starting with jq (sed-like tool for JSON)

roles/arteria-delivery-ws/defaults/main.yml, roles/arteria-delivery-ws/templates/delivery_app.config.j2
Latest `arteria-delivery` includes support for delivering projects consisting of multiple runfolders. For this to work we need a directory where the service can setup symlinks between the relevant sources to include in the delivery.
=> Test latest arteria-delivery

roles/arteria-siswrap-ws/tasks/sisyphus.yml
An other PDL dependency seems to suddenly fail some of its tests. This workaround just installs the dependency before PDL, and then asks for the tests to be skipped. It might perhaps introduce some weird behaviour downstream (untested), but if that is the case then we'll just have to solve it then.
=> Workaround for failing PDL dependency tests

README.md, install.yml, roles/arteria-staging/defaults/main.yml, roles/arteria-staging/meta/main.yml, roles/arteria-staging/tasks/main.yml, roles/arteria-staging/templates/arteria-staging.screen, roles/arteria-staging/templates/arteria-staging.screen.j2, roles/arteria-staging/templates/start-arteria-staging.j2, roles/arteria-staging/templates/stop-arteria-staging.j2
This will make it somewhat easier to start/stop Arteria staging services. 
Note that in this variant the screen will start a specific version of the services. Which version that gets started is decided by what the current production environment sets in `PATH`. To make it possible to iterate through many staging versions while not having to update the production environment we're therefore setting `PATH` to `../staging/latest/`.
=> Start/stop scripts for Arteria staging services

roles/ngi-methylseq/tasks/main.yml
Only bismark will be used for production, so @ewels prefer just one alias. This is something not urgent so will be included in next release.
=> remove unwanted alias for ngi-methylseq

ansible.cfg
This will increase the performance of Ansible slightly. As default it only keeps the SSH connections open for 1 minute, so lets increase it to 60 minutes. Pipelining reduces the number of SSH operations required for executing a module. Can cause problems when combined with sudo, but that's not an issue for us.
=> Increase the performance slightly

roles/archive-upload-ws/defaults/main.yml
This needs to be deployed on irma1 so that the new archive workflows for Irma can be tested on mm-xart002.
=> Test rc1 in staging env

roles/archive-upload-ws/templates/archive_upload_app.config.j2
remove empty path from exclude_from_tarball list which caused everything to be excluded
=> remove path to exclude from archive

roles/tarzan/defaults/main.yml, roles/tarzan/tasks/dependencies.yml, roles/tarzan/tasks/main.yml
Kong does no longer generate its start script in the bin directory of
the lua runtime when installed via luarocks. So instead we install from
source, which for the most part does the exact same thing
Meanwhile, according to the kong docs
(https://getkong.org/install/source/), it is recommended to use the lua
runtime that comes with openresty. So I also reordered the installation process a little and removed installing the standalone luajit.
=> kong/lua: fix broken kong deployment

host_vars/127.0.0.1/main.yml, roles/archive-upload-ws/tasks/main.yml, roles/arteria-checksum-ws/tasks/main.yml, roles/arteria-delivery-ws/tasks/main.yml, roles/arteria-siswrap-ws/tasks/main.yml, roles/arteria-siswrap-ws/tasks/sisyphus.yml, roles/methylseq/tasks/main.yml, roles/multiqc/tasks/main.yml, roles/nextflow/tasks/main.yml, roles/ngi-neutronstar/tasks/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ngi_reports/tasks/main.yml, roles/nougat/tasks/main.yml, roles/rnaseq/tasks/main.yml, roles/sarek/tasks/main.yml, roles/taca/tasks/main.yml, roles/tarzan/tasks/main.yml, roles/ugc/tasks/main.yml, tasks/post-install.yml
As discussed with @b97pla , this is a preliminary way (in future can be extend to make it fancier with more info) to have tool versions within the deployed environment. It also creates an `alias` called `deploy_env` to fetch that info easily
```
[~$] deployed_env
-- devel (default) --
Anaconda: conda 4.1.6
NGI Pipeline: 061dc824237e1b95aca76d1c0ecfea0108c779f7
Nextflow: 0.31.1
Kong: 0.12.3
Luarocks: 2.4.3
Cassandra: 2.2.5
Openresty: 1.11.2.5
Serf: 0.7.0
TACA: 30a256ef7fc40c8ceaf199145ae1fa7a34cdc4b9
taca-ngi-pipeline: c6b803b3e9e116294387ec83e6fd96cece6737aa
StatusDB: ca2a3faea82a10359c70f7a7697db499b5c82b17
flowcell_parser: e4750ce700026b1e7427de712d1464049d222a88
ngi_reports: c782f7b97f8e9f672af9ae18d5426b20cb13a77b
ngi_visualizations: 1bdc2d51d8588ec3067ada873adadb0aa661251d
MultiQC: …
```
=> LOG versions for tools installed within deployment

roles/archive-upload-ws/defaults/main.yml, roles/archive-upload-ws/templates/archive_upload_app.config.j2
This PR updates the current version of the archive-upload arteria micro service to 1.0.0 and adds some necessary config parameters
=> bump archive-upload version, include necessary parameters

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
This config change is relevant to this [PR](https://github.com/NationalGenomicsInfrastructure/ngi_pipeline/pull/380)
=> ngi_pipeline set qc make_md5

roles/archive-upload-ws/defaults/main.yml
Every time snpseq-archive-upload is called with the upload or reupload endpoint a dsmc command is started and the output of this command is written to a dsmc_output-file. However, old errors from previous uploading or reuploading can cause issues when we later parse this log for errors. Release v.1.0.1 of snpseq-archive-upload includes a fix where a new log file is created when the service is called and the old log file is moved to a new file with a timestamp.
This fix is not tested thoroughly in staging environment. However, snpseq_packs.archive_upload_workflow and snpseq_packs.archive_missing_files_workflow runs without errors on mm-xart001 with the service running on mm-xart002.
=> Updated snpseq-archive-upload to v1.0.1

roles/multiqc/defaults/main.yml, roles/multiqc/templates/multiqc_config.yml.j2
To tie in with https://github.com/ewels/MultiQC_NGI/commit/13daca016813eabd89dc81c376ebc7d13dae6d42 so that Uppsala does not have the Swedac ISO accreditation badge in the MultiQC report footer.
=> Set MultiQC config.swedac_accredited according to NGI node

roles/arteria-siswrap-ws/defaults/main.yml, roles/multiqc/defaults/main.yml, roles/nextflow/defaults/main.yml
This PR will deploy the latest Nextflow release which should include a fix for slurm-issues. In addition, it specifies versions for MultiQC_NGI and Sisyphus.
=> Use nextflow snapshot

README.md, sync.py
This removes the `--delete` parameter to the rsync command so that old environments will not be removed from lupus during sync even if they have been removed from irma3.
For convenience, the build command includes the commands for generating the staging environment name.
=> removed delete parameter from rsync command

roles/sarek/files/sarek_irma.config
I'll make these changes to Sarek repo as well, but I think it's faster to get it in production this way.
=> Added fix for Sarek wasteful resource usage due to wrong queue

.gitattributes
Assuming that all `.config` files in this repo are for Nextflow, this file will force GitHub to use Nextflow syntax highlighting. Minor thing, but helps spot syntax errors :)
=> Format .config files with Nextflow syntax highlighting on GitHub

roles/multiqc/defaults/main.yml
The new version solves the issue of the yaml load warning display.
=> Bump multiqc_ngi version

host_vars/127.0.0.1/main.yml
We want to update the latest stage deployment with this so that the yam.load warning does not show up any more.
=> Updated ngi-pipeline to fix yaml.load warning

roles/nextflow/tasks/main.yml, roles/nextflow/templates/nextflow_irma_site.config, roles/rnaseq/tasks/main.yml, roles/rnaseq/templates/rnaseq_site.config
My take on what I think @ewels was saying today (please correct me if I misunderstood something).
This would remove the need for `-profile uppmax` and instead replace it with a general irma nextflow config file. The long term goal is to use `nf-core download` inside of the playbook to remove a lot of code.
=> Irma nextflow config

roles/methylseq/tasks/main.yml, roles/rnaseq/tasks/main.yml
Bugfix for the aliases of methylseq and rnaseq.
=> Needed backslashes for newlines

roles/sarek/tasks/main.yml, roles/taca/tasks/main.yml, roles/taca/templates/site_taca_sarek_delivery.yml.j2
During testing, it was discovered that the delivery README was incorrectly staged for sarek data. 
I thought 
```
- {{ ngi_resources }}/TACA/{{ site }}.DELIVERY.README.SAREK.txt
- <STAGINGPATH>/DELIVERY.README.SAREK.txt
```
would stage `{{ site }}.DELIVERY.README.SAREK.txt` as `DELIVERY.README.SAREK.txt`, but instead TACA makes a folder called `DELIVERY.README.SAREK.txt` and puts the README there, e.g :
```
staging_path
|__ DELIVERY.README.SAREK.txt
|__ upps.DELIVERY.README.SAREK.txt
```
To tackle this problem, the delivery configs are now written without prefixes and are put in separate folders.
=> Write site specific resources to separate folders

roles/archive-upload-ws/tasks/1_install.yml, roles/arteria-checksum-ws/tasks/1_install.yml, roles/arteria-delivery-ws/defaults/main.yml, roles/multiqc/tasks/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ngi_reports/tasks/dependencies.yml, roles/ngi_reports/tasks/main.yml, roles/taca/tasks/dependencies.yml, roles/taca/tasks/main.yml, roles/taca/templates/site_taca_cleanup.yml.j2, roles/ugc/tasks/main.yml, tasks/post-install.yml
This PR makes our roles and playbooks compatible with Ansible 2.9.
While I was at it, I also made some style changes and replaced all invocations of `pip` via shell with the ansible `pip` module.
On irma I installed ansible-2.9 besides our current (2.0) installation and symlinked `/lupus/ngi/irma3/ansible-env` to the ansible-2.0 installation. Once we merge this PR, we need to change that symlink to point to the 2.9 installation instead.
=> Make playbooks and roles compatible with Ansible 2.9

install.yml, roles/nextflow/defaults/main.yml, roles/nf-core-biocontainer-temp/defaults/main.yml, roles/nf-core-biocontainer-temp/tasks/main.yml, roles/nf-core-biocontainer-temp/templates/site.config.j2, roles/nf-core/defaults/main.yml, roles/ngi_pipeline/templates/sourceme_common.sh.j2
- Created a new temporary role to install rnaseq v3 until `nf-core download` is updated to handle biocontainers. 
- rnaseqv3 also requires nextflow v20.10.0.
=> Update to rnaseq3 with new temp role, bump nextflow to v20.10.0

roles/nextflow/defaults/main.yml
Phil said we need this nextflow version to get rnaseq v3.0 to work properly.
=> Update nextflow release to get rnaseq to work

roles/archive-upload-ws/defaults/main.yml, roles/archive-upload-ws/meta/main.yml, roles/archive-upload-ws/tasks/1_install.yml, roles/arteria-checksum-ws/defaults/main.yml, roles/arteria-checksum-ws/meta/main.yml, roles/arteria-checksum-ws/tasks/1_install.yml, roles/arteria-staging/defaults/main.yml, roles/arteria-staging/templates/arteria-staging.screen.j2, roles/nextflow/defaults/main.yml, roles/nf-core-biocontainer-temp/tasks/main.yml
Fixes a problem where virtual envs for `arteria-checksum` and `archive-upload` would be created with python 3 rather than 2.
Also: Fixed "v" missing from nextflow version and updated synchronize parameters to avoid issues with permissions.
=> Bimonthly: fix arteria services

host_vars/127.0.0.1/main.yml
A tiny change to include in the monthly release.
=> Update ngi_pipeline version to increase default qc walltime

host_vars/127.0.0.1/main.yml, roles/multiqc/defaults/main.yml, roles/ngi_reports/defaults/main.yml, roles/sarek/tasks/main.yml, roles/taca/defaults/main.yml, roles/taca/templates/create_delivery_readme_softlinks.sh.j2
**Updates**
* ngi-pipeline : pinned inflect for py2.7.
* taca-ngi-pipeline: Add new RNASeq and Sarek delivery readmes for Sthlm.
* Flowcell parser:  Fix data format for NextSeq2000.
* TACA: Various updates to support NextSeq2000.
* Multiqc: Updated to v1.10
* ngi_reports: Support for NextSeq2000 and updates to text from SWEDAC regarding deviations.
=> Bump TACA, flowcell parser, taca-ngi-pipeline, ngi-pipeline and add new app Readmes for Sthlm

roles/multiqc/tasks/main.yml, roles/nf-core/defaults/main.yml, roles/taca/defaults/main.yml
Updates
* nfcore/methylseq: Version bump to v1.6
* nfcore/nanoseq: New addition at v1.1.0
* TACA: Updates to NextSeq2000 flow and additional 10x index types and masks
* Flowcell parser: Updates to NextSeq 2000 flow
* multiqc: Remove the temporary matplotlib fix at v3.2.2 (fixed in multiqc v1.10).
=> Bump methylseq,fc_parser,TACA, add nanoseq, cleanup multiqc role

roles/multiqc/defaults/main.yml, roles/taca/defaults/main.yml
Updates
- Multiqc to v1.11
- Update TACA version
@ssjunnebo Should we include the recent updates to taca-ngi-pipeline too?
=> Update multiqc to 1.11 and bump TACA version

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/sarek/tasks/main.yml, roles/sarek/templates/DELIVERY.README.SAREK.WES.md.j2, roles/taca/tasks/main.yml, roles/taca/templates/site_taca_sarek_wes_delivery.yml.j2
In this PR the following changes are included:
- When running Sarek the parameter --generate_gvcf will be added as default.
- A new README.md for WES analysed with Sarek is now available.
- A new TACA-config for staging of WES analysed with Sarek is now available.
=> Sarek wes defaults upps

roles/taca/tasks/main.yml
We will just remove the Sarek WES config for Sthlm for now. We can add it back in the future if we need it.
=> Remove Sthlm Sarek WES config for now

roles/taca/templates/site_taca_sarek_wes_delivery.yml.j2
Extra space in line 37 gave following error: 
```
File "/lupus/ngi/production/v1.27/sw/anaconda/envs/NGI/lib/python2.7/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
"expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
in "/lupus/ngi/production/latest/conf/TACA/upps_taca_sarek_wes_delivery.yml", line 12, column 9
expected <block end>, but found '<block sequence start>'
```
=> removed extra space in site_taca_sarek_wes_delivery.yml.j2

roles/nextflow/tasks/main.yml
Nextflow tries to create a plugins directory if it doesn't exist, but only users in the ngi-sw group have write access.
=> Set up required plugins dir for nextflow
