NationalGenomicsInfrastructure/irma-provision

README.md, bootstrap/bashrc
As well as how things are configured, and how the environment was setup/bootstrapped from the beginning.
=> Add an initial README with some very basic how to run Ansible

README.md, host_vars/127.0.0.1
Compile piper devel instead of master. Add some comments for recompiling in readme.
=> Use piper devel branch

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Made sure all envvar's look good from Scilife @ solna's side. Minor tweaks.
=> Verified irma config. Added a missing envvar

deploy.yml, roles/funk_004/defaults/main.yml, roles/funk_004/tasks/main.yml, roles/funk_004/templates/crontab_ngi2016001.j2, roles/funk_004/templates/start_supervisord_funk_004.sh.j2, roles/funk_004/templates/supervisord_funk_004.conf.j2
Could perhaps be done better in more general/agnostics roles,
but this will do for now.
=> Initial role for some funk_004 specific configs/settings.

host_vars/127.0.0.1, roles/ngi_pipeline/defaults/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/ngi_pipeline/templates/sourceme.sh.j2, roles/ngi_pipeline/templates/sourceme_common.sh.j2, roles/ngi_pipeline/templates/sourceme_site.sh.j2, roles/tarzan/tasks/dependencies.yml, roles/tarzan/tasks/main.yml
@sylvinite it seems to work fine on a `ansible-playbook deploy.yml --tags ngi_pipeline`. Next step would be to test a whole deploy, and then of course to see how it works inside the cluster. Do you have any comments on this so far?
=> Initial support for multiple NGI site configs.

roles/funk_006/defaults/main.yml, roles/funk_006/tasks/main.yml, roles/funk_006/templates/crontab_ngi2016003.j2, roles/funk_006/templates/start_supervisord_funk_006.sh.j2, roles/funk_006/templates/supervisord_funk_006.conf.j2
I'm a criminal, crim-i-naaaal.
=> Robbed funk_004 and applied to funk_006

roles/ngi_pipeline/tasks/main.yml
=> Permissions quickfix

roles/funk_004/templates/supervisord_upps.conf.j2, roles/funk_006/templates/supervisord_sthlm.conf.j2, roles/ngi_pipeline/tasks/main.yml, sync.py
- correct swp filter in find command in sync.py
- use the ngi venv variable instead of using the hard coded anaconda path
=> Anaconda path

README.md, roles/piper/templates/gen_GATK_ref.sh.j2, sync.py
Also update the README with info about anaconda and setgid.
And add an exception for the sync of the gatk_bundle
=> Update script to generate gatk indices and symlink in the reference data

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Words cannot express the sheer size of this PR.
Several men have worked their whole lives, and died, altering this information.
=> Biggest revision known to man

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
=> Minor flowcell change

README.md, roles/piper/templates/gen_GATK_ref.sh.j2
Updated readme, commented out magical tabix.
=> Updated readme, commented out magical tabix

roles/ngi_pipeline/tasks/main.yml
Doesn't work when we are several ppl doing installs
=> Don't run chmod on anaconda

host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml
Small things for the deployment
=> Version updates, taca dep fix

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/piper/defaults/main.yml, roles/piper/tasks/dependencies.yml, roles/piper/tasks/main.yml, roles/piper/tasks/prereqs.yml
Uses a pre-built version of Piper manually placed under /lupus/ngi/irma3/piper_src/
=> Ugly fix for latest Piper version

host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml, roles/taca/tasks/dependencies.yml, roles/taca/tasks/main.yml
Minor stuff revised so I can consider the TACA role finished.
=> TACA final fixes

README.md
Made some really small additions, but it seems to have confused github quite a lot.
=> Small readme note

install_checksum.yml, roles/checksum-ws/README.md, roles/checksum-ws/Vagrantfile, roles/checksum-ws/bootstrap_vagrant_box.sh, roles/checksum-ws/defaults/main.yml, roles/checksum-ws/tasks/1_install.yml, roles/checksum-ws/tasks/2_install_config.yml, roles/checksum-ws/tasks/main.yml, roles/checksum-ws/templates/checksum_app.config.j2, roles/checksum-ws/templates/checksum_logger.config.j2
This is a preliminary playbook and role used to install the checksum service. Still needs to have supervisord, etc setup. But I'll leave that to someone else. :wink:
=> Deploy checksum service

roles/taca/templates/sthlm_fastq_taca_delivery.yml.j2
Pretty self explanatory. Miniature fix.
=> Small path fix to get the fastq delivery working

host_vars/127.0.0.1/main.yml, roles/ngi_reports/tasks/main.yml
New ngi_reports version supports custom paths to config files. Changed the code to accommodate this. Also made very minor aesthetic fixes.
=> Minor upgrades to make ngi_reports functional

README.md, host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/tasks/main.yml, roles/ngi_reports/tasks/main.yml, roles/ngi_reports/templates/ngi_reports_sthlm.conf.j2, roles/ngi_reports/templates/ngi_reports_upps.conf.j2
Minor changes related to:
Readme
NGI Pipeline - Broke out Envvar name
NGI Reports - Added necessary log file support, some bugfixes
=> NGI reports related updates

install.yml, roles/multiqc/tasks/main.yml
Really did not expect MultiQC to install this easy. Sometimes you win I suppose.
=> Added multiQC support

roles/ngi_reports/templates/ngi_reports_site.conf.j2
Should just automerge this, but you know. Standards.
=> Invalid ASCII. Seriously.

install.yml, roles/multiqc/files/multiqc_config.yml, roles/multiqc/tasks/main.yml
MultiQC was superslow since it tried to connect to the net. Added config file to go around it.
=> Solved multiqc timeout error

roles/ngi_reports/templates/ngi_reports_site.conf.j2
NGI reports is sure being picky today.
=> ngi reports config fix

roles/taca/tasks/main.yml, roles/taca/templates/site_taca_delivery.yml.j2
Changed conditionals order for taca template.
Also added FASTQ files to the fake deliveries.
=> Added fastq files to fake delivery

roles/multiqc/defaults/main.yml, roles/multiqc/tasks/main.yml, roles/taca/templates/site_taca_delivery.yml.j2
Taca deliveries had a folder mismatch.
MultiQC was requested to be pulled from source. As such, script has been altered to reflect this
=> MultiQC source & taca config fix

roles/ngi_pipeline/files/fastq_screen.irma.conf
=> Updated fastq_screen reference to igenomes

host_vars/127.0.0.1/main.yml
=> Updated ngi_pipeline version; now handles weirder project names

README.md, roles/taca/templates/site_taca_delivery.yml.j2, roles/taca/templates/sthlm_fastq_taca_delivery.yml.j2
Also made a small update in README.md to account for the irma3 home directory problem.
=> Fixed TACA's ngi_reports delivery statements

install.yml, roles/ngi-rnaseq/defaults/main.yml, roles/ngi-rnaseq/tasks/main.yml, roles/ngi-rnaseq/templates/nextflow.config.j2
=> NGI-RNAseq role/recipe

roles/taca/defaults/main.yml, roles/taca/tasks/main.yml, roles/taca/templates/sthlm_fastq_delivery.yml.j2
Version update most notable sets a better sender for TACA messages.
Extra delivery configs to easily deliver fastq files to irma.
=> Updated taca version, created additional delivery configs

roles/multiqc/defaults/main.yml, roles/multiqc/tasks/main.yml, roles/multiqc/templates/multiqc_config.yml.j2
Primarily fixes a problem with samples sometimes being missing.
=> MultiQC version bump

roles/nougat/defaults/main.yml, roles/nougat/templates/NouGAT_config.conf.j2
Should fix the problems the first irma nougat deployment was experiencing.
=> NouGAT version bump

roles/multiqc/templates/multiqc_config.yml.j2
These are specific to NGI pipelines, so shouldn't be added to core MultiQC. So this is the place to put them.
=> Added MultiQC log extension clean patterns

roles/ngi-rnaseq/tasks/main.yml
Task got wiped out during development. Reimplemented and tested.
=> rnaseq recipe now downloads nextflow

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
I completely place the blame on Denis for introducing this problem.
=> Fixed syntax error in ngi_pipeline config

roles/func_accounts/templates/crontab_upps.j2
These were relevant on Nestor; an other solution is being implemented for Irma.
=> Remove reports stats cronjob for Uppsala 

roles/taca/defaults/main.yml, roles/taca/templates/site_taca_delivery.yml.j2
Use version of TACA that supports copy of project reports to an outbox for easier download.
=> New TACA reports feature for Uppsala

README.md, bootstrap/bootstrap.sh
Bit of a cleanup to the README. Also added a very simplistic bootstrap bash script that can be run the first time instead of having to guess what to do from the previous README instructions.
=> Add a bootstrap script and make the README a bit more clear

roles/multiqc/templates/multiqc_config.yml.j2, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Also fixed the multiqc config to work properly.
=> Added test cores for staging

roles/multiqc/tasks/main.yml, roles/multiqc/templates/multiqc_config.yml.j2, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Oh how I love when configuration files can only handle incredibly specific input.
=> Fixed ngi_pipeline & multiqc configs

roles/ngi-rnaseq/defaults/main.yml, tasks/pre-install.yml
Forgot to update the version of NGI-RNAseq. Good thing it's not central to the next release or anything.
=> Updated ngi-rnaseq version

sync.py, tasks/post-install.yml, tasks/pre-install.yml
Not assigning anyone since I need to triple-check the logic. It works, but it should also make sense.
=> Wildwest is now be globally editable

roles/taca/defaults/main.yml
=> TACA version bump, fixes a unicode error for cleanup command

roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
Loading R caused a reload of java, switching version from 1.7 to 1.8
=> removed R from modules to load

host_vars/127.0.0.1/main.yml, roles/ngi-rnaseq/defaults/main.yml, roles/ngi-rnaseq/tasks/main.yml, roles/ngi_pipeline/templates/sourceme_common.sh.j2
Take two of upgrading NGI_Pipeline.
NGI_Pipeline points to a temporary branch for staging. Module load piper in bashrc has been removed. RNA-seq branch has been updated, and necessary nextflow envvars have been set.
=> NGI_Pipeline staging take 2

host_vars/127.0.0.1/main.yml, roles/arteria-checksum-ws/defaults/main.yml, roles/arteria-siswrap-ws/defaults/main.yml, roles/multiqc/defaults/main.yml, roles/ngi_pipeline/defaults/main.yml, roles/ngi_pipeline/files/uppnex_datadeliver, roles/ngi_pipeline/tasks/main.yml, roles/ngi_pipeline/templates/sourceme_site.sh.j2, roles/ngi_reports/defaults/main.yml, roles/nougat/defaults/main.yml, roles/taca/defaults/main.yml, roles/tarzan/defaults/main.yml
Script that is used by Uppsala for making manual deliveries into INBOXes. Adds this to our PATH.
=> Add uppnex_datadeliver script to be used by funk_004

host_vars/127.0.0.1/main.yml, install.yml, roles/standalone_scripts/defaults/main.yml, roles/standalone_scripts/tasks/main.yml
4 NGI Pipeline merges, woo!
Also Standalone Scripts on a separate recipe might be a bit excessive, but I guess people will add more stuff to it relatively soon.
=> NGI_Pipeline now on regular branch; standalone scripts included

host_vars/127.0.0.1/main.yml
Last piece for the next staging release :)
=> Switched NGI_Pipeline to temporary stage branch

roles/ngi-rnaseq/defaults/main.yml, roles/ngi-rnaseq/tasks/dependencies.yml, roles/ngi-rnaseq/tasks/main.yml, roles/ngi_pipeline/templates/sourceme_site.sh.j2
Nextflow module is no longer autoloaded
Fixed reversed project numbers
Reversed back to local nextflow installation.
=> Nextflow changes

roles/ngi-rnaseq/defaults/main.yml
=> Updated rnaseq version

install.yml, roles/arteria-delivery-ws/defaults/main.yml, roles/arteria-delivery-ws/tasks/install.yml, roles/arteria-delivery-ws/tasks/main.yml, roles/arteria-delivery-ws/templates/delivery_alembic.ini.j2, roles/arteria-delivery-ws/templates/delivery_app.config.j2, roles/arteria-delivery-ws/templates/delivery_logger.config.j2, roles/arteria-siswrap-ws/defaults/main.yml
Used for handling deliveries via Mover and SUPR.
This is primarily configured for staging purposes. Small changes needs to be done for production.
=> Deploy arteria-delivery webservice on irma1 

roles/arteria-delivery-ws/tasks/main.yml
Otherwise it will be hard for it to start.. :)
=> Add missing conf to supervisord

roles/ngi-rnaseq/files/install_R_dependencies.r, roles/ngi-rnaseq/tasks/dependencies.yml, roles/ngi-rnaseq/tasks/main.yml, roles/ngi-rnaseq/templates/ngi-rnaseq_site.config, roles/taca/defaults/main.yml
**ngi-rnaseq**
Cleared unnecessary config sections
Added R dependency download
Removed NXF_WORK possibly being under /scratch
**taca**
Version update for some cleanup procedures
=> Updated ngi-rnaseq dependencies, updated taca version

host_vars/127.0.0.1/main.yml, roles/ngi-rnaseq/tasks/dependencies.yml
This is a bit hard to test since my account has ngi-sw priviledges. 
Will do a staging push, test quickly, and hope for the best.
=> Removed nextflow workfiles ngi group

host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml
TACA -> Cleanup irma stuff (mostly)
ngi-pipeline -> GT concordance
=> Update TACA and NGIPIPELINE to latest version

README.md, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2
gt_concordance config still needs some work, but currently there is none, and piper version 1.5.1 needs to go into production asap.
=> Cleaned up Readme, slightly improved gt_concordance config

roles/ngi-rnaseq/tasks/dependencies.yml
Putting workfiles under current directoy is apparently the best way to handle them. Workfiles are temporary logs and working files.
=> Fixed another nextflow-irma issue

roles/arteria-delivery-ws/defaults/main.yml
Need to push this version out in a staging environment to validate the whole flow from Uppsala sequencers -> delivered to customer.
=> Will validate vs arteria-delivery 1.0.0-rc1

roles/arteria-delivery-ws/defaults/main.yml
This fixes a couple of issues found when integration testing arteria-delivery on Irma.
=> arteria-delivery: new bugfix

roles/nougat/defaults/main.yml, roles/nougat/tasks/dependencies.yml, roles/nougat/templates/NouGAT_config.conf.j2
The permissions might need a review since I am unsure about them.
Kmergenie explictly needed `u+x` to even consider running.
=> Addded kmergenie for nougat

roles/nougat/defaults/main.yml
=> Updated NouGAT version to support kmergenie

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/templates/sourceme_site.sh.j2, roles/taca/tasks/dependencies.yml
Feel free to comment if there is a cleaner way to archieve this.
=> Added SNIC credentials support for stockholm

roles/ngi-rnaseq/defaults/main.yml
New version for `RNA-seq` pipeline that fixes some minor bugs.
=> update RNA-seq bug fixes version

roles/multiqc/tasks/main.yml, roles/multiqc/templates/multiqc_config.yml.j2
Moved ssh keypaths directly into the template. Removed indentation which remained in the final template.
=> Fixed multiqc staging conf issues

roles/ngi-rnaseq/templates/ngi-rnaseq_site.config
Jun noticed that MultiQC wasn't running properly in the pipeline. Made me a @ewels realise that this command was wrong.
=> Changed to correct command

.gitignore, README.md, host_vars/127.0.0.1/main.yml, roles/taca/defaults/main.yml, roles/taca/tasks/dependencies.yml
Updated taca-ngi to *fixed* mover version
Added orderportal-ngi credential file
Reorganized the readme file to make it easier to use
=> Mover fixes

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/templates/sourceme_site.sh.j2, roles/taca/defaults/main.yml
Will deploy these as .1 hotfixes.
=> Mover staging fixes

.gitignore, host_vars/127.0.0.1/main.yml, install.yml, roles/multiqc/defaults/main.yml, roles/nextflow/tasks/main.yml, roles/ngi-methylseq/defaults/main.yml, roles/ngi-methylseq/tasks/main.yml, roles/ngi-methylseq/templates/ngi-methylseq_site.config, roles/ngi-rnaseq/defaults/main.yml, roles/ngi-rnaseq/tasks/main.yml, roles/nougat/defaults/main.yml, roles/nougat/tasks/dependencies.yml
Some changes relevant for new version deployment on `irma`, as mentioned [here](https://trello.com/c/HoKzsY4j/812-irma-v-19)
=> changes for new version

roles/nextflow/tasks/main.yml, roles/ngi-rnaseq/tasks/main.yml, roles/ngi-rnaseq/templates/ngi-rnaseq_site.config, roles/nougat/defaults/main.yml, roles/nougat/tasks/dependencies.yml, roles/nougat/templates/Singularity_runtime_script.j2, roles/taca/templates/site_taca_delivery.yml.j2
Added experimental nougat
Fixed some minor issues from last PR
Removed unnecessary taca comment
=> Experimental nougat, minor fixes

roles/ngi-methylseq/defaults/main.yml, roles/ngi-methylseq/tasks/main.yml, roles/ngi-methylseq/templates/ngi-methylseq_site.config
Needs testing and revision... ;)
=> NGI-MethylSeq - use singularity image.

install.yml, roles/archive-upload-ws/defaults/main.yml, roles/archive-upload-ws/tasks/1_install.yml, roles/archive-upload-ws/tasks/2_install_config.yml, roles/archive-upload-ws/tasks/main.yml, roles/archive-upload-ws/templates/archive_upload_app.config.j2, roles/archive-upload-ws/templates/archive_upload_logger.config.j2
Should be mostly similar to what we do locally on biotank, with some differences with the values in the config. This might not work 100% yet though, as it was some time since I last tested this.
=> Initial role for archive-upload from Irma

roles/archive-upload-ws/defaults/main.yml
- corrected path to monitored directory
- harmonized path to linked archives root directory
=> correct archive service config paths

install.yml
`CAW` will soon be replaced by `Sarek`, so until then actually don't do anything about that role
=> Dont include CAW

roles/taca/templates/site_taca_delivery.yml.j2
=> Fix typo in TACA config

roles/func_accounts/templates/crontab_sthlm.j2, roles/func_accounts/templates/crontab_upps.j2
Include a crontab entry to also update Charon with run info for analysis running with the Sarek pipeline
=> crontab entries to update charon for sarek pipeline

roles/nextflow/tasks/main.yml
Removed NXF_WORK definition from Irma bashrc.
=> Removed NXF_WORK definition from Irma bashrc

roles/standalone_scripts/defaults/main.yml, roles/standalone_scripts/tasks/main.yml
This PR introduces deployment of standalone scripts specific to the Uppsala site
=> added standalone scripts for uppsala

host_vars/127.0.0.1/main.yml
This updates the ngi_pipeline to a version that supports cleaning of sarek work directory and parsing sarek results into Charon.
=> update ngi_pipeline version

README.md
.. primarily regarding reloading crontabs and services
=> some clarification on deployments in README

host_vars/127.0.0.1/main.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/sarek/files/sarek_irma.config, roles/sarek/tasks/main.yml, roles/sarek/templates/sarek_exec_site.sh.j2
Introduces an irma-specific config for Sarek that complements the existing configuration.
Bumps the `ngi_pipeline` version used.
=> Irma specs in sarek config

host_vars/127.0.0.1/main.yml, roles/arteria-delivery-ws/defaults/main.yml, roles/nextflow/defaults/main.yml
New versions of Nextflow (19.04.1), Sarek (2.3.FIX1) and arteria-delivery (v2.3.0)
=> bumped nextflow, sarek and arteria-delivery

host_vars/127.0.0.1/main.yml
- Updates the ngi_pipeline version to the latest
=> updated ngi_pipeline version

roles/arteria-delivery-ws/defaults/main.yml
This PR bumps the version of the Arteria-delivery service.
=> bumped arteria-delivery version

roles/methylseq/templates/methylseq_site.config
Config values that we have been supplying for the methylseq at ngi-sthlm.
Might be more adjustments needed for really large projects.
=> Methylseq config

host_vars/127.0.0.1/main.yml, roles/arteria-delivery-ws/defaults/main.yml, roles/arteria-siswrap-ws/defaults/main.yml, roles/ngi_pipeline/templates/irma_ngi_config.yaml.j2, roles/standalone_scripts/defaults/main.yml, roles/standalone_scripts/tasks/main.yml
Mostly updated versions of software..
=> Update software versions

roles/standalone_scripts/tasks/main.yml
We get a syntax error without the quotes.
=> Fix syntax

roles/methylseq/templates/methylseq_site.config
The previous fix for qualimap increased the memory and cpus, but that did not make things better. Let's hope this one does.
=> Methylseq qualimap bugfix just made things worse

roles/ampliseq/tasks/main.yml, roles/atacseq/tasks/main.yml
Changed the order of the configs.
=> Update irma config for atacseq and ampliseq

roles/multiqc/templates/multiqc_config.yml.j2
Updated multiqc config with the url of our new database
=> Update sthlm database url

roles/multiqc/templates/multiqc_config.yml.j2, roles/taca/tasks/main.yml, roles/taca/templates/site_taca_runfolder_delivery.yml.j2
Updated the latest server changes in the MultiQC config and added the config file for TACA runfolder delivery.
=> Add v18 changes

roles/ngi_reports/defaults/main.yml
New version og ngi reports with updated text.
=> Update ngi reports version

roles/taca/templates/site_taca_delivery.yml.j2
Replace Sisyphus with seqreports and remove genotype concordance for Uppsala
=> Update TACA config Uppsala

roles/nf-core/tasks/main.yml
Had some troubles with Sarek when I figured out nf-core was using the local singularity cache.
=> Add singularity cache for nf-core role

roles/nf-core/defaults/main.yml, roles/nf-core/tasks/main.yml, roles/nf-core/templates/site.config.j2, roles/taca/templates/site_app_specific_delivery.yml.j2, roles/taca/templates/site_fastq_delivery.yml.j2, roles/taca/templates/site_taca_delivery.yml.j2, roles/taca/templates/site_taca_runfolder_delivery.yml.j2
* Added more parameters for ampliseq.
* Added parameter to ignore lib_prep in xml generation in ngi_reports
* Updated methylseq version
=> Changed ampliseq, methylseq version and xml generation in report.

host_vars/127.0.0.1/main.yml, roles/multiqc/tasks/main.yml, roles/ngi_pipeline/tasks/main.yml
Multiqc 1.9 works best with python3.6 and up.
=> Bump multiqc and add an env with python 3.8

roles/taca/defaults/main.yml
Update the latest changes to be tested on irma.
=> Update TACA: py3 compatibility and more

roles/nextflow/tasks/main.yml, roles/nextflow/templates/nextflow_irma_site.config.j2
This PR updates the uppsala nextflow config so that it does not contain custom parameters for the MultiQC process. 
I also added a jinja2 suffix to the template.
=> Update uppsala nextflow conf

roles/multiqc/defaults/main.yml
For py3 compatibility of multiqc_ngi
=> Update multiqc_ngi version

README.md, sync.py
Created a `monthly` branch to make PRs to as well. This can be merged to master before the production deployment. 
We could have a bimonthly branch for sarek/nf-core changes.
=> Update sync to make dryrun optional and to specify a particular deployment directory

sync.py
Missed updating the symlink when specifying a deployment in sync.py.
=> Update code to add symlink in sync.py

roles/arteria-delivery-ws/defaults/main.yml
This PR adds a solution to a problem that has been solved on the bimonthly branch already.
=> Cherry-pick from bimonthly to solve arteria-delivery issue

roles/nextflow/templates/nextflow_irma_site.config.j2
Not sure how to make it case insensitive, so this seemed like the next best thing.
=> Process name change on rnaseqv3.0

roles/ngi_pipeline/tasks/main.yml, roles/ngi_reports/defaults/main.yml
* ngi_reports: Bug fix for NextSeq 2000 flow
* ngi_pipeline: Update sourcing for Sthlm.
=> Update ngi_reports and sourcing for sthlm

roles/ngi_reports/defaults/main.yml
Updates
*  ngi_reports:  Update to account for changed library construction values.
=> Bump ngi_reports for new construction values

roles/archive-upload-ws/defaults/main.yml, roles/multiqc/defaults/main.yml, roles/nf-core/defaults/main.yml, roles/taca/defaults/main.yml
- methylseq (1.6->1.6.1)
- ampliseq (1.1.2->1.2.0)
- atacseq (1.1.0->1.2.1)
- multiqc (1.10->v1.10.1)
- snpseq-archive-upload (1.0.2 ->1.0.3)
- taca ngi pipeline
=> Stage deployment May 2021

install.yml, roles/dds/tasks/main.yml
Temporary role for testing the new Data delivery system on irma
=> Temp role for dds testing

roles/dds/tasks/main.yml, roles/nextflow/defaults/main.yml, roles/nf-core/defaults/main.yml
* Bump nextflow version to v21.04.1
* Delete dds role
=> Bump nextflow version and delete temp dds role

install.yml
=> Remove dds role

host_vars/127.0.0.1/main.yml, roles/archive-upload-ws/defaults/main.yml
* Sarek from v2.6.1 to v2.7
* archive_upload_ws from v1.0.3 to v1.0.4
=> Bump sarek and archive_upload_ws

host_vars/127.0.0.1/main.yml, roles/nextflow/defaults/main.yml, roles/taca/defaults/main.yml
* Small encoding fixes in TACA and ngi_pipeline
* Nextflow version for offline usage to avoid issues with plugins
=> Py3 and nf fixes

install.yml, roles/dds_cli/defaults/main.yml, roles/dds_cli/tasks/main.yml
=> Add dds_cli for testing
